#ifndef SYSTEM_H
#define SYSTEM_H

#define FOSC 14745600 
#define BAUD 9600
#define UART_BUFFER_SIZE 20
#define MOTION_CONTROLLER_FREQ 20 // in hertz
#define DEPTH_CALIBRATION_SLOPE 1
#define DEPT_CALIBRATION_INTERCEPT 0

#endif
