#ifndef SYSTEM_H
#define SYSTEM_H

#define FOSC 14745600 
#define BAUD 9600
#define MCB_BUFFER_SIZE 4
#define PRESSURE_SENSOR_FREQ 20 // in hertz
#define DEPTH_CALIBRATION_SLOPE 1
#define DEPT_CALIBRATION_INTERCEPT 0

#endif
